// flow-typed signature: 5b1bec580ed73ca5105f427277f08ac8
// flow-typed version: <<STUB>>/koa-better-router_v2.1.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-better-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-better-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-better-router/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-better-router/index' {
  declare module.exports: $Exports<'koa-better-router'>;
}
declare module 'koa-better-router/index.js' {
  declare module.exports: $Exports<'koa-better-router'>;
}
declare module 'koa-better-router/utils.js' {
  declare module.exports: $Exports<'koa-better-router/utils'>;
}
