// flow-typed signature: 177f0c7f231f34930e590def16c06432
// flow-typed version: <<STUB>>/snabbdom-pragma_v2.6.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snabbdom-pragma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snabbdom-pragma' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snabbdom-pragma/dist/index.es6' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/dist/index' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/src/fn' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/src/index' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/src/is' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/build-specs/dist-file/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/build-specs/dist-file/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/build-test' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/component/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/component/transform-babel' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/component/transform-buble' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/component/transform-traceur' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/component/transform-typescript' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-attributes/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-babel' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-buble' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-traceur' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-typescript' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-class-names/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-babel' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-buble' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-traceur' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-typescript' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-event/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-event/transform-babel' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-event/transform-buble' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-event/transform-traceur' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/element-with-event/transform-typescript' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/simple-element/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/simple-element/transform-babel' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/simple-element/transform-buble' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/simple-element/transform-traceur' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-specs/simple-element/transform-typescript' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/jsx-test' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/pragma-specs/vnode-text-and-var/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/pragma-specs/vnode-text-and-var/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/pragma-specs/vnode-text/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/pragma-specs/vnode-text/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/pragma-specs/vnode-type/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/pragma-specs/vnode-type/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/pragma-specs/vnode-with-array-children/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/pragma-specs/vnode-with-array-children/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/pragma-specs/vnode-with-children/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/pragma-specs/vnode-with-children/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/pragma-test' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-class-names/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-class-names/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-class-names/neutral' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-component-with-slot/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-component-with-slot/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-component/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-component/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria-object/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria-object/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-events/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-events/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-events/neutral' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-forced-attrs/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-forced-attrs/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-hard-component/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-hard-component/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-hooks/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-hooks/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-hooks/neutral' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-mixed-module-ways/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-mixed-module-ways/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-properties/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-properties/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-reserved-module/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-reserved-module/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-style/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-style/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-svg/actual' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-svg/expected' {
  declare module.exports: any;
}

declare module 'snabbdom-pragma/test/snabbdom-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snabbdom-pragma/dist/index.es6.js' {
  declare module.exports: $Exports<'snabbdom-pragma/dist/index.es6'>;
}
declare module 'snabbdom-pragma/dist/index.js' {
  declare module.exports: $Exports<'snabbdom-pragma/dist/index'>;
}
declare module 'snabbdom-pragma/src/fn.js' {
  declare module.exports: $Exports<'snabbdom-pragma/src/fn'>;
}
declare module 'snabbdom-pragma/src/index.js' {
  declare module.exports: $Exports<'snabbdom-pragma/src/index'>;
}
declare module 'snabbdom-pragma/src/is.js' {
  declare module.exports: $Exports<'snabbdom-pragma/src/is'>;
}
declare module 'snabbdom-pragma/test/build-specs/dist-file/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/build-specs/dist-file/actual'>;
}
declare module 'snabbdom-pragma/test/build-specs/dist-file/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/build-specs/dist-file/expected'>;
}
declare module 'snabbdom-pragma/test/build-test.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/build-test'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/component/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/component/actual'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/component/transform-babel.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/component/transform-babel'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/component/transform-buble.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/component/transform-buble'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/component/transform-traceur.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/component/transform-traceur'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/component/transform-typescript.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/component/transform-typescript'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-attributes/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-attributes/actual'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-babel.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-babel'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-buble.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-buble'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-traceur.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-traceur'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-typescript.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-attributes/transform-typescript'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-class-names/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-class-names/actual'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-babel.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-babel'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-buble.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-buble'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-traceur.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-traceur'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-typescript.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-class-names/transform-typescript'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-event/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-event/actual'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-event/transform-babel.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-event/transform-babel'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-event/transform-buble.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-event/transform-buble'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-event/transform-traceur.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-event/transform-traceur'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/element-with-event/transform-typescript.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/element-with-event/transform-typescript'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/simple-element/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/simple-element/actual'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/simple-element/transform-babel.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/simple-element/transform-babel'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/simple-element/transform-buble.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/simple-element/transform-buble'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/simple-element/transform-traceur.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/simple-element/transform-traceur'>;
}
declare module 'snabbdom-pragma/test/jsx-specs/simple-element/transform-typescript.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-specs/simple-element/transform-typescript'>;
}
declare module 'snabbdom-pragma/test/jsx-test.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/jsx-test'>;
}
declare module 'snabbdom-pragma/test/pragma-specs/vnode-text-and-var/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/pragma-specs/vnode-text-and-var/actual'>;
}
declare module 'snabbdom-pragma/test/pragma-specs/vnode-text-and-var/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/pragma-specs/vnode-text-and-var/expected'>;
}
declare module 'snabbdom-pragma/test/pragma-specs/vnode-text/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/pragma-specs/vnode-text/actual'>;
}
declare module 'snabbdom-pragma/test/pragma-specs/vnode-text/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/pragma-specs/vnode-text/expected'>;
}
declare module 'snabbdom-pragma/test/pragma-specs/vnode-type/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/pragma-specs/vnode-type/actual'>;
}
declare module 'snabbdom-pragma/test/pragma-specs/vnode-type/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/pragma-specs/vnode-type/expected'>;
}
declare module 'snabbdom-pragma/test/pragma-specs/vnode-with-array-children/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/pragma-specs/vnode-with-array-children/actual'>;
}
declare module 'snabbdom-pragma/test/pragma-specs/vnode-with-array-children/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/pragma-specs/vnode-with-array-children/expected'>;
}
declare module 'snabbdom-pragma/test/pragma-specs/vnode-with-children/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/pragma-specs/vnode-with-children/actual'>;
}
declare module 'snabbdom-pragma/test/pragma-specs/vnode-with-children/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/pragma-specs/vnode-with-children/expected'>;
}
declare module 'snabbdom-pragma/test/pragma-test.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/pragma-test'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-class-names/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-class-names/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-class-names/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-class-names/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-class-names/neutral.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-class-names/neutral'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-component-with-slot/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-component-with-slot/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-component-with-slot/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-component-with-slot/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-component/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-component/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-component/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-component/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria-object/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria-object/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria-object/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria-object/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-data-aria/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-events/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-events/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-events/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-events/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-events/neutral.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-events/neutral'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-forced-attrs/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-forced-attrs/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-forced-attrs/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-forced-attrs/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-hard-component/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-hard-component/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-hard-component/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-hard-component/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-hooks/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-hooks/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-hooks/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-hooks/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-hooks/neutral.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-hooks/neutral'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-mixed-module-ways/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-mixed-module-ways/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-mixed-module-ways/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-mixed-module-ways/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-properties/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-properties/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-properties/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-properties/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-reserved-module/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-reserved-module/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-reserved-module/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-reserved-module/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-style/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-style/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-style/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-style/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-svg/actual.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-svg/actual'>;
}
declare module 'snabbdom-pragma/test/snabbdom-specs/vnode-svg/expected.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-specs/vnode-svg/expected'>;
}
declare module 'snabbdom-pragma/test/snabbdom-test.js' {
  declare module.exports: $Exports<'snabbdom-pragma/test/snabbdom-test'>;
}
